/* ============================================================
   Liquid Tab — built-in quote library
   Each entry: [text, author, category]
   ============================================================ */

const QUOTE_CATEGORIES = {
  stoic:      "Stoic",
  philosophy: "Philosophy",
  literature: "Literature",
  science:    "Science",
  artists:    "Artists & Musicians",
  motivation: "Motivation",
  zen:        "Zen",
};

const QUOTES = [
  // ---------------- Stoic ----------------
  ["You have power over your mind — not outside events. Realize this, and you will find strength.", "Marcus Aurelius", "stoic"],
  ["Waste no more time arguing about what a good man should be. Be one.", "Marcus Aurelius", "stoic"],
  ["The impediment to action advances action. What stands in the way becomes the way.", "Marcus Aurelius", "stoic"],
  ["If it is not right, do not do it; if it is not true, do not say it.", "Marcus Aurelius", "stoic"],
  ["Confine yourself to the present.", "Marcus Aurelius", "stoic"],
  ["Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", "Marcus Aurelius", "stoic"],
  ["We suffer more often in imagination than in reality.", "Seneca", "stoic"],
  ["Luck is what happens when preparation meets opportunity.", "Seneca", "stoic"],
  ["It is not that we have a short time to live, but that we waste a lot of it.", "Seneca", "stoic"],
  ["Difficulties strengthen the mind, as labour does the body.", "Seneca", "stoic"],
  ["Every new beginning comes from some other beginning's end.", "Seneca", "stoic"],
  ["He who fears death will never do anything worthy of a living man.", "Seneca", "stoic"],
  ["It's not what happens to you, but how you react to it that matters.", "Epictetus", "stoic"],
  ["First say to yourself what you would be; and then do what you have to do.", "Epictetus", "stoic"],
  ["No man is free who is not master of himself.", "Epictetus", "stoic"],
  ["Wealth consists not in having great possessions, but in having few wants.", "Epictetus", "stoic"],
  ["Don't explain your philosophy. Embody it.", "Epictetus", "stoic"],
  ["Man is disturbed not by things, but by the views he takes of them.", "Epictetus", "stoic"],

  // ---------------- Philosophy ----------------
  ["The unexamined life is not worth living.", "Socrates", "philosophy"],
  ["I know that I know nothing.", "Socrates", "philosophy"],
  ["He who has a why to live can bear almost any how.", "Friedrich Nietzsche", "philosophy"],
  ["He who fights with monsters should look to it that he himself does not become a monster.", "Friedrich Nietzsche", "philosophy"],
  ["You must have chaos within you to give birth to a dancing star.", "Friedrich Nietzsche", "philosophy"],
  ["Life can only be understood backwards; but it must be lived forwards.", "Søren Kierkegaard", "philosophy"],
  ["Anxiety is the dizziness of freedom.", "Søren Kierkegaard", "philosophy"],
  ["In the midst of winter, I found there was, within me, an invincible summer.", "Albert Camus", "philosophy"],
  ["The struggle itself toward the heights is enough to fill a man's heart.", "Albert Camus", "philosophy"],
  ["Man is condemned to be free.", "Jean-Paul Sartre", "philosophy"],
  ["The journey of a thousand miles begins with a single step.", "Lao Tzu", "philosophy"],
  ["Knowing others is intelligence; knowing yourself is true wisdom.", "Lao Tzu", "philosophy"],
  ["When I let go of what I am, I become what I might be.", "Lao Tzu", "philosophy"],
  ["It does not matter how slowly you go as long as you do not stop.", "Confucius", "philosophy"],
  ["The man who moves a mountain begins by carrying away small stones.", "Confucius", "philosophy"],
  ["Real knowledge is to know the extent of one's ignorance.", "Confucius", "philosophy"],
  ["The limits of my language mean the limits of my world.", "Ludwig Wittgenstein", "philosophy"],
  ["We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Will Durant", "philosophy"],

  // ---------------- Literature ----------------
  ["It does not do to dwell on dreams and forget to live.", "J.K. Rowling", "literature"],
  ["Not all those who wander are lost.", "J.R.R. Tolkien", "literature"],
  ["All we have to decide is what to do with the time that is given us.", "J.R.R. Tolkien", "literature"],
  ["The only way out of the labyrinth of suffering is to forgive.", "John Green", "literature"],
  ["It is not in the stars to hold our destiny but in ourselves.", "William Shakespeare", "literature"],
  ["We know what we are, but know not what we may be.", "William Shakespeare", "literature"],
  ["There is no greater agony than bearing an untold story inside you.", "Maya Angelou", "literature"],
  ["You may not control all the events that happen to you, but you can decide not to be reduced by them.", "Maya Angelou", "literature"],
  ["Beware; for I am fearless, and therefore powerful.", "Mary Shelley", "literature"],
  ["The most beautiful things in the world cannot be seen or touched, they are felt with the heart.", "Antoine de Saint-Exupéry", "literature"],
  ["A reader lives a thousand lives before he dies.", "George R.R. Martin", "literature"],
  ["Whatever you do, don't be boring.", "Ernest Hemingway", "literature"],
  ["There is nothing to writing. All you do is sit down at a typewriter and bleed.", "Ernest Hemingway", "literature"],
  ["The world breaks everyone, and afterward, many are strong at the broken places.", "Ernest Hemingway", "literature"],
  ["Everything you can imagine is real.", "Pablo Picasso", "literature"],
  ["Tomorrow is always fresh, with no mistakes in it yet.", "L.M. Montgomery", "literature"],
  ["We are all in the gutter, but some of us are looking at the stars.", "Oscar Wilde", "literature"],
  ["Be yourself; everyone else is already taken.", "Oscar Wilde", "literature"],

  // ---------------- Science ----------------
  ["Imagination is more important than knowledge.", "Albert Einstein", "science"],
  ["Life is like riding a bicycle. To keep your balance you must keep moving.", "Albert Einstein", "science"],
  ["Try not to become a man of success, but rather try to become a man of value.", "Albert Einstein", "science"],
  ["The important thing is not to stop questioning.", "Albert Einstein", "science"],
  ["Nothing in life is to be feared, it is only to be understood.", "Marie Curie", "science"],
  ["Be less curious about people and more curious about ideas.", "Marie Curie", "science"],
  ["Somewhere, something incredible is waiting to be known.", "Carl Sagan", "science"],
  ["We are made of star stuff.", "Carl Sagan", "science"],
  ["Extraordinary claims require extraordinary evidence.", "Carl Sagan", "science"],
  ["The first principle is that you must not fool yourself — and you are the easiest person to fool.", "Richard Feynman", "science"],
  ["I would rather have questions that can't be answered than answers that can't be questioned.", "Richard Feynman", "science"],
  ["Study hard what interests you the most, in the most undisciplined and original manner possible.", "Richard Feynman", "science"],
  ["If I have seen further it is by standing on the shoulders of giants.", "Isaac Newton", "science"],
  ["Intelligence is the ability to adapt to change.", "Stephen Hawking", "science"],
  ["Look up at the stars and not down at your feet.", "Stephen Hawking", "science"],
  ["Science is a way of thinking much more than it is a body of knowledge.", "Carl Sagan", "science"],
  ["Nature uses only the longest threads to weave her patterns.", "Richard Feynman", "science"],
  ["What we know is a drop, what we don't know is an ocean.", "Isaac Newton", "science"],

  // ---------------- Artists & Musicians ----------------
  ["Without music, life would be a mistake.", "Friedrich Nietzsche", "artists"],
  ["Music is the universal language of mankind.", "Henry Wadsworth Longfellow", "artists"],
  ["To play a wrong note is insignificant; to play without passion is inexcusable.", "Ludwig van Beethoven", "artists"],
  ["Music can change the world because it can change people.", "Bono", "artists"],
  ["Music is the silence between the notes.", "Claude Debussy", "artists"],
  ["Learn the changes, then forget them.", "Charlie Parker", "artists"],
  ["Do not fear mistakes. There are none.", "Miles Davis", "artists"],
  ["Sometimes you have to play a long time to be able to play like yourself.", "Miles Davis", "artists"],
  ["I never practice; I always play.", "Wanda Landowska", "artists"],
  ["Everything you can imagine, nature has already created.", "Salvador Dalí", "artists"],
  ["I dream my painting and then I paint my dream.", "Vincent van Gogh", "artists"],
  ["Great things are done by a series of small things brought together.", "Vincent van Gogh", "artists"],
  ["I am always doing that which I cannot do, in order that I may learn how to do it.", "Pablo Picasso", "artists"],
  ["Every child is an artist. The problem is how to remain an artist once we grow up.", "Pablo Picasso", "artists"],
  ["Inspiration exists, but it has to find you working.", "Pablo Picasso", "artists"],
  ["Creativity takes courage.", "Henri Matisse", "artists"],
  ["I paint flowers so they will not die.", "Frida Kahlo", "artists"],
  ["Art washes away from the soul the dust of everyday life.", "Pablo Picasso", "artists"],

  // ---------------- Motivation ----------------
  ["The secret of getting ahead is getting started.", "Mark Twain", "motivation"],
  ["It is never too late to be what you might have been.", "George Eliot", "motivation"],
  ["Whether you think you can or you think you can't, you're right.", "Henry Ford", "motivation"],
  ["Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill", "motivation"],
  ["Fall seven times, stand up eight.", "Japanese proverb", "motivation"],
  ["The best time to plant a tree was twenty years ago. The second best time is now.", "Chinese proverb", "motivation"],
  ["Do not wait to strike till the iron is hot; but make it hot by striking.", "William Butler Yeats", "motivation"],
  ["Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", "Stephen King", "motivation"],
  ["If you want to build a ship, teach people to long for the endless immensity of the sea.", "Antoine de Saint-Exupéry", "motivation"],
  ["Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.", "Antoine de Saint-Exupéry", "motivation"],
  ["What you do today can improve all your tomorrows.", "Ralph Marston", "motivation"],
  ["The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson", "motivation"],
  ["Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson", "motivation"],
  ["Simplicity is the ultimate sophistication.", "Leonardo da Vinci", "motivation"],
  ["Well done is better than well said.", "Benjamin Franklin", "motivation"],
  ["Either write something worth reading or do something worth writing.", "Benjamin Franklin", "motivation"],
  ["Discipline equals freedom.", "Jocko Willink", "motivation"],
  ["Start where you are. Use what you have. Do what you can.", "Arthur Ashe", "motivation"],

  // ---------------- Zen ----------------
  ["Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.", "Zen proverb", "zen"],
  ["The obstacle is the path.", "Zen proverb", "zen"],
  ["When you reach the top of the mountain, keep climbing.", "Zen proverb", "zen"],
  ["Sitting quietly, doing nothing, spring comes, and the grass grows by itself.", "Matsuo Bashō", "zen"],
  ["Do not seek to follow in the footsteps of the wise. Seek what they sought.", "Matsuo Bashō", "zen"],
  ["In the beginner's mind there are many possibilities, in the expert's mind there are few.", "Shunryu Suzuki", "zen"],
  ["Each morning we are born again. What we do today matters most.", "Buddha", "zen"],
  ["Peace comes from within. Do not seek it without.", "Buddha", "zen"],
  ["The mind is everything. What you think you become.", "Buddha", "zen"],
  ["No mud, no lotus.", "Thích Nhất Hạnh", "zen"],
  ["Walk as if you are kissing the earth with your feet.", "Thích Nhất Hạnh", "zen"],
  ["Smile, breathe and go slowly.", "Thích Nhất Hạnh", "zen"],
  ["Nature does not hurry, yet everything is accomplished.", "Lao Tzu", "zen"],
  ["Silence is a source of great strength.", "Lao Tzu", "zen"],
  ["Let go, or be dragged.", "Zen proverb", "zen"],
  ["Wherever you are, be there totally.", "Eckhart Tolle", "zen"],
  ["The quieter you become, the more you can hear.", "Ram Dass", "zen"],
  ["Empty your cup so that it may be filled.", "Bruce Lee", "zen"],
];
