/* ============================================================
   Liquid Tab — built-in quote library
   Each entry: [text, author, category]
   ============================================================ */

const QUOTE_CATEGORIES = {
  alex:  "Alex Hormozi",
  leila: "Leila Hormozi",
};

const QUOTES = [
  // ---------------- Alex Hormozi ----------------
  ["You don't become confident by shouting affirmations in the mirror, but by having a stack of undeniable proof that you are who you say you are. Outwork your self-doubt.", "Alex Hormozi", "alex"],
  ["A focused fool can accomplish more than a distracted genius.", "Alex Hormozi", "alex"],
  ["Volume negates luck.", "Alex Hormozi", "alex"],
  ["The degree of the pain will determine the degree of the solution needed.", "Alex Hormozi", "alex"],
  ["You have to do the boring work that nobody wants to do for longer than anyone else is willing to do it.", "Alex Hormozi", "alex"],
  ["Make offers so good people feel stupid saying no.", "Alex Hormozi", "alex"],
  ["You don't have a motivation problem, you have a clarity problem.", "Alex Hormozi", "alex"],
  ["If you can't decide between two choices, pick the harder one. It builds character.", "Alex Hormozi", "alex"],
  ["The work works. Just keep doing it.", "Alex Hormozi", "alex"],
  ["If you want to be successful, you must become comfortable being misunderstood for long periods of time.", "Alex Hormozi", "alex"],
  ["Skill is the bridge between desire and reality.", "Alex Hormozi", "alex"],
  ["Don't measure your progress by how you feel. Measure it by what you did.", "Alex Hormozi", "alex"],
  ["Most people don't fail because of lack of talent; they fail because they quit before the compound effect kicks in.", "Alex Hormozi", "alex"],
  ["The person who can endure the most boredom wins.", "Alex Hormozi", "alex"],
  ["Simple scales, fancy fails.", "Alex Hormozi", "alex"],
  ["You are not tired from doing too much. You are tired from doing too little of what matters.", "Alex Hormozi", "alex"],
  ["The best way to build confidence is to do the things you told yourself you were going to do.", "Alex Hormozi", "alex"],
  ["If it were easy, everyone would do it. The difficulty is the barrier to entry that protects your upside.", "Alex Hormozi", "alex"],
  ["The single greatest hack in business is doing what you said you would do, when you said you would do it.", "Alex Hormozi", "alex"],
  ["Impatience with actions, patience with results.", "Alex Hormozi", "alex"],
  ["You don't need another course, you need more reps.", "Alex Hormozi", "alex"],
  ["The pain of regret is far worse than the pain of discipline.", "Alex Hormozi", "alex"],
  ["Stop looking for the secret. The secret is that you have to do the thing 10,000 times.", "Alex Hormozi", "alex"],
  ["Ignorance is the only reason people aren't rich. If you knew how to make a million dollars, you would have already done it.", "Alex Hormozi", "alex"],
  ["Hard times create strong people. Embrace the suck.", "Alex Hormozi", "alex"],
  ["Success comes down to doing the obvious thing for an uncomfortably long period of time.", "Alex Hormozi", "alex"],
  ["Overnight success is a 10-year story packed into a 10-minute podcast.", "Alex Hormozi", "alex"],
  ["Fear of failure is just fear of looking foolish to people whose opinions don't matter.", "Alex Hormozi", "alex"],
  ["The market doesn't care about your effort, it only cares about your value.", "Alex Hormozi", "alex"],
  ["If you want to make more money, solve bigger problems for wealthier people.", "Alex Hormozi", "alex"],
  ["Speed is a competitive advantage. Slow is expensive.", "Alex Hormozi", "alex"],
  ["Action creates clarity. Inaction creates anxiety.", "Alex Hormozi", "alex"],
  ["You are paying an ignorance tax on everything you don't know how to do yet.", "Alex Hormozi", "alex"],
  ["If you want to change your life, change what you do every day between 6 AM and 8 AM, or 6 PM and 8 PM.", "Alex Hormozi", "alex"],
  ["Don't judge the day by the harvest you reap, but by the seeds you plant.", "Alex Hormozi", "alex"],

  // ---------------- Leila Hormozi ----------------
  ["Culture isn't what you say on the wall, it's what you tolerate in the hall.", "Leila Hormozi", "leila"],
  ["You cannot scale a business until you scale yourself as a leader.", "Leila Hormozi", "leila"],
  ["The quality of your business is determined by the quality of the conversations you're avoiding.", "Leila Hormozi", "leila"],
  ["Great leadership is not about being liked, it's about holding people to the standard they committed to.", "Leila Hormozi", "leila"],
  ["If you want a team that takes ownership, you have to give them the room to actually own things.", "Leila Hormozi", "leila"],
  ["Clarity breeds confidence, ambiguity breeds anxiety.", "Leila Hormozi", "leila"],
  ["Discipline is choosing between what you want now and what you want most.", "Leila Hormozi", "leila"],
  ["A bad hire costs you time, money, and energy. A great hire gives you your life back.", "Leila Hormozi", "leila"],
  ["You don't build a massive company by doing everything yourself; you build it by building people.", "Leila Hormozi", "leila"],
  ["Feedback is a gift, but only if you have the maturity to unwrap it without getting defensive.", "Leila Hormozi", "leila"],
  ["The fastest way to burn out your top performers is by tolerating low performers.", "Leila Hormozi", "leila"],
  ["Stop trying to manage time. Start managing your energy and your priorities.", "Leila Hormozi", "leila"],
  ["Resilience isn't never falling down. It's how quickly you get back up and figure out what went wrong.", "Leila Hormozi", "leila"],
  ["The standard you walk past is the standard you accept.", "Leila Hormozi", "leila"],
  ["When you feel overwhelmed, look at what you can simplify, delegate, or eliminate.", "Leila Hormozi", "leila"],
  ["True confidence comes from keeping promises to yourself when nobody else is watching.", "Leila Hormozi", "leila"],
  ["Hiring is not about finding someone who can do the job; it's about finding someone who thrives in your environment.", "Leila Hormozi", "leila"],
  ["You don't grow during the comfortable seasons, you grow in the fire of solving tough problems.", "Leila Hormozi", "leila"],
  ["Process isn't bureaucracy — process is how you protect your team from chaos.", "Leila Hormozi", "leila"],
  ["If you want people to respect your boundaries, you have to be the first one who respects them.", "Leila Hormozi", "leila"],
  ["Your business will only grow to the extent of your ability to manage stress and uncertainty.", "Leila Hormozi", "leila"],
  ["Don't lower the bar so people can jump over it. Raise their skills so they can clear the bar.", "Leila Hormozi", "leila"],
  ["Empathy without accountability is just enablement.", "Leila Hormozi", "leila"],
  ["Momentum is hard to build and easy to lose. Protect it at all costs.", "Leila Hormozi", "leila"],
  ["Lead by example first, instructions second.", "Leila Hormozi", "leila"],
];
